package org.jblooming.waf.constants;

public interface AnagraphicalDataConstants {

// form fields
  String FLD_ANAGRAPHICALDATA_ID = "AD_ID";
  String FLD_LOCATIONDESCRIPTION = "FLD_LOCATIONDESCRIPTION";
  String FLD_ADDRESS = "FLD_ADDRESS";
  String FLD_CITY = "FLD_CITY";
  String FLD_TELEPHONE = "FLD_TELEPHONE";
  String FLD_FAX = "FLD_FAX";
  String FLD_EMAIL = "FLD_EMAIL";
  String FLD_URL = "FLD_URL";
  String FLD_STATE = "FLD_STATE";
  String FLD_PROVINCE = "FLD_PROVINCE";
  String FLD_MOBILE = "FLD_MOBILE";
  String FLD_ZIP = "FLD_ZIP";
  String FLD_COUNTRY = "COUNTRY";
  String FLD_BIRT_CITY = "FLD_BIRT_CITY";

  String FLD_SERVICE_LOCATIONDESCRIPTION = "SERVICE_LOCATIONDESCRIPTION";
  String FLD_SERVICE_ADDRESS = "SERVICE_ADDRESS";
  String FLD_SERVICE_URL = "SERVICE_URL";

  String FLD_OTHERTELEPHONE = "FLD_OTHERTELEPHONE";
  String FLD_OTHERTELDESCRIPTION = "FLD_OTHERTELDESCRIPTION";
  String FLD_HIDEANAGRAPHICALDATA = "FLD_HIDEANAGRAPHICALDATA";

  String I18N_NO_ANAGR_DATA = "NO_ANAGR_DATA";


}
