package org.jblooming.waf.constants;



public interface AgendaConstants {


  String AGENDA = "AGE";

// form fields

  String FLD_FOCUSED_DATE = Fields.FORM_PREFIX + AGENDA +"FOCUSED_DATE";
  String FLD_OBJECT = Fields.FORM_PREFIX + AGENDA +"FLD_OBJECT";
  String FLD_START = Fields.FORM_PREFIX + AGENDA +"FLD_START";
  String FLD_START_HOUR = Fields.FORM_PREFIX + AGENDA +"FLD_START_HOUR";
  String FLD_END = Fields.FORM_PREFIX + AGENDA +"FLD_END";
  String FLD_END_HOUR = Fields.FORM_PREFIX + AGENDA +"FLD_END_HOUR";
  String FLD_DURATION = Fields.FORM_PREFIX + AGENDA +"FLD_DURATION";
  String FLD_TYPE = Fields.FORM_PREFIX + AGENDA +"FLD_TYPE";

  String FLD_RECURRENT_EVERY = Fields.FORM_PREFIX + AGENDA +"RECURRENT_EVERY";
  String FLD_RECURRENT_HOWMANYTIMES = Fields.FORM_PREFIX + AGENDA +"RECURRENT_HOWMANYTIMES";


  String FLD_RECURRENT_MINUTE_EVERY = Fields.FORM_PREFIX + AGENDA +"RECURRENT_MINUTE_EVERY";

  String FLD_RECURRENT_MONTHLY = Fields.FORM_PREFIX + AGENDA +"RECURRENT_MONTHLY";


  String FLD_RECURRENT_MONTHLY_DAYS = Fields.FORM_PREFIX + AGENDA +"RECURRENT_MONTHLY_DAYS";
  String FLD_RECURRENT_MONTHLY_MONTHSNUMBER = Fields.FORM_PREFIX + AGENDA +"RECURRENT_MONTHLY_MONTHSNUMBER";

  String FLD_RECURRENT_MONTHLY_HOWMANYTIMES = Fields.FORM_PREFIX + AGENDA +"RECURRENT_MONTHLY_HOWMANYTIMES";
  String FLD_RECURRENT_WEEKLY_HOWMANYTIMES = Fields.FORM_PREFIX + AGENDA +"RECURRENT_WEEKLY_HOWMANYTIMES";
  String FLD_RECURRENT_DAILY_HOWMANYTIMES = Fields.FORM_PREFIX + AGENDA +"RECURRENT_DAILY_HOWMANYTIMES";
  String FLD_RECURRENT_MINUTE_HOWMANYTIMES = Fields.FORM_PREFIX + AGENDA +"RECURRENT_MINUTE_HOWMANYTIMES";

  String FLD_RECURRENT_YEARLY_HOWMANYTIMES = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_HOWMANYTIMES";

  String FLD_RECURRENT_DAILY_EVERY = Fields.FORM_PREFIX + AGENDA +"RECURRENT_DAILY_EVERY";
  String FLD_RECURRENT_WEEKLY_EVERY = Fields.FORM_PREFIX + AGENDA +"RECURRENT_WEEKLY_EVERY";

  String FLD_RECURRENT_YEARLY = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY";
  String FLD_RECURRENT_YEARLY_HOWMANYTIMES_1 = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_HOWMANYTIMES_1";
  String FLD_RECURRENT_MONTHLY_WEEKS = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_MONTHLY_WEEKS";
  String FLD_RECURRENT_YEARLY_WEEKS = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_WEEKS";
  String FLD_RECURRENT_YEARLY_DAYS = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_DAYS";
  String FLD_RECURRENT_YEARLY_DAYNUMBER = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_DAYNUMBER";
  String FLD_RECURRENT_YEARLY_MONTH = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_MONTH";
  String FLD_RECURRENT_YEARLY_MONTH_1 = Fields.FORM_PREFIX + AGENDA +"FLD_RECURRENT_YEARLY_MONTH_1";

  String FLD_ESTIMATED_DURATION = Fields.FORM_PREFIX + AGENDA +"FLD_ESTIMATED_DURATION";

  String FLD_NAME = Fields.FORM_PREFIX + AGENDA +"FLD_NAME";


  String I18N_OF = "OF";

  String I18N_PREVIOUS_MONTH = "PREVIOUS_MONTH";
  String I18N_NEXT_MONTH = "NEXT_MONTH";
  String I18N_TODAY = "TODAY";

  String I18N_DAYS = "DAYS";

  String I18N_WEEKS = "WEEKS";
  String I18N_MONTHS = "MONTHS";
  String I18N_FIRST = "FIRST";
  String I18N_SECOND = "SECOND";
  String I18N_THIRD = "THIRD";
  String I18N_FOURTH = "FOURTH";

// other constants
  String I18N_LAST = "I18N_LAST";
}
