package org.jblooming.waf.constants;

public interface OperatorConstants extends SecuredNodeConstants {

  String FLD_NAME = "FLD_NAME";
  String FLD_SURNAME = "FLD_SURNAME";
  String FLD_IS_ENABLED = "FLD_IS_ENABLED";
  String FLD_LOGOUT_TIME = "LOGOUT_TIME";
  String FLD_LOGIN_COOKIES = "LOGIN_COOKIES";
  String RECENT_VIEWS_SIZE = "RECENT_VIEWS_SIZE";
  String FLD_WORKING_HOUR_BEGIN = "WORKING_HOUR_BEGIN";
  String FLD_WORKING_HOUR_END = "WORKING_HOUR_END";
  String FLD_WORKING_HOUR_TOTAL = "WORKING_HOUR_TOTAL";
  String FLD_HOUR_DAY_START = "HOUR_DAY_START";
  String FLD_HOUR_DAY_END = "HOUR_DAY_END";
  String FLD_SELECT_LANG = "SELECT_LANG";
  String FLD_CURRENT_SKIN = "CURRENT_SKIN";

  String FLD_LOGIN_NAME = "FLD_LOGIN_NAME";
  String FLD_PWD = "FLD_PWD";
  String FLD_PWD_RETYPE = "FLD_PWD_RETYPE";
  String FLD_LOGIN_NEW_PWD = "USER_LOGIN_NEW_PWD";
  String FLD_LOGIN_NEW_PWD_RETYPE = "USER_LOGIN_NEW_PWD_RETYPE";
  String FLD_ADMINISTRATOR = "FLD_ADMINISTRATOR";


  // other constants
  int SYSTEM_OPERATOR_ID = -2;
  String SYSTEM_OPERATOR = "SYSTEM_OPERATOR";

  String PASSWORD_MASK = "0_12345678_9";

  String OP_PAGE_SIZE = "OP_PAGE_SIZE";

  String SEND_EVENT_BY_ICAL = "SEND_EVENT_BY_ICAL";
  String MEDIA_PREFERRED_CHANNEL = "MEDIA_PREFERRED_CHANNEL";
  String NOTIFY_MY_EVENTS_TO_MYSELF = "NOTIFY_MY_EVENTS_TO_MYSELF";

}